remotes::install_github("uribo/jpndistrict")
remotes::install_github("haleyjeppson/ggmosaic")
install.packages("ggridge")
install.packages("daggity")
install.packages("ggdag")
install.packages("rdrobust")
install.packages("rdd")
install.packages("titanic")
