#!/bin/bash

export QUARTO_VERSION="1.2.280"
sudo curl -o quarto-linux-amd64.deb -L https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb
sudo gdebi quarto-linux-amd64.deb

Rscript setup_cran.R

Rscript setup_gh.R

rm apt.txt README.md environment.yml postBuild setup_cran.R setup_gh.R
