install.packages("daggity",  dependencies = TRUE, repos = "https://cran.ism.ac.jp/")
install.packages("ggdag",    dependencies = TRUE, repos = "https://cran.ism.ac.jp/")
install.packages("rdd",      dependencies = TRUE, repos = "https://cran.ism.ac.jp/")
install.packages("rdrobust", dependencies = TRUE, repos = "https://cran.ism.ac.jp/")
install.packages("gsynth",   dependencies = TRUE, repos = "https://cran.ism.ac.jp/")
